# Macro file for the initialization of example B4
# in interactive session
#
# Set some default verbose
#


/control/verbose 2
/control/saveHistory
/run/verbose 0

# geometry control

/DetIn/NLay 3                            # lower than 10
/DetIn/DimX 2                            # int
/DetIn/DimY 2                            # int
/DetIn/SizeXY 4.44 mm
/DetIn/PCB_thic 1.6 mm
/DetIn/SpaceX 1 mm
/DetIn/SpaceY 1 mm
/DetIn/BotDist 34.4 mm
/DetIn/TopDist 20.4 mm
/DetIn/SideDist 19.9 mm
/DetIn/KWRad 10 mm
/DetIn/KWThic 0.0127 mm
/DetIn/KWZ 10 mm
/DetIn/KWSwitch 0                        # int 0 or 1
/DetIn/KWh 8 mm                          # same as /BeamIn/Focus/Y
/DetIn/LayThic 0.5 mm
/DetIn/LayGap 7. mm





# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 1
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac


# Beam control
/BeamIn/A 238
/BeamIn/Z 92
/BeamIn/KEu 796 MeV
/BeamIn/Dpp 0.0
/BeamIn/Focus/X -0.3 cm
/BeamIn/Focus/DX 0.0 cm
/BeamIn/Focus/Y 0.9 cm
/BeamIn/Focus/DY 0.0 cm
/BeamIn/Focus/Z 10 cm
/BeamIn/Focus/maxAta 100 mrad
/BeamIn/Focus/maxBta 0 mrad
/BeamIn/Focus/Ata0 0 mrad #-144 mrad
/BeamIn/Focus/Bta0 0 mrad



/BeamIn/Report

#/run/beamOn 500